# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: e-shop-application

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

plugins:
  - serverless-s3-sync

resources:
      Resources:
        StaticSite:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: PublicRead
            BucketName: cars-e-shop-angular
            WebsiteConfiguration:
              IndexDocument: index.html

        StaticSiteS3BucketPolicy:
          Type: AWS::S3::BucketPolicy
          Properties:
            Bucket:
              Ref: StaticSite
            PolicyDocument:
              Statement:
                - Sid: PublicReadGetObject
                  Effect: Allow
                  Principal: "*"
                  Action:
                    - s3:GetObject
                  Resource:
                    Fn::Join: [
                      "", [
                        "arn:aws:s3:::",
                        {
                          "Ref": "StaticSite"
                        },
                        "/*"
                      ]
                    ]
custom:
  s3Sync:
    - bucketName: cars-e-shop-angular
      localDir: dist/app
      deleteRemoved: false
      acl: public-read
      defaultContentType: application/json

